name: release

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - id: package-name
        name: Get package name
        run: |
            TAG="${{ github.event.release.tag_name }}"
            PACKAGE="${TAG%@v*}"

            echo "tag=$TAG" >> "$GITHUB_OUTPUT"
            echo "package=$PACKAGE" >> "$GITHUB_OUTPUT"
      - id: checkout
        name: Checkout code
        uses: actions/checkout@v7
      - id: setup-node
        name: Setup node with pnpm
        uses: ./.github/actions/setup-node-pnpm
        with:
          node-version: ${{ matrix.node-version }}
          install-deps: true
      - name: Navigate to package directory
        run: cd packages/${{ steps.package-name.outputs.package }}
      - id: tests
        name: Run tests
        run: pnpm test
        background: true
      - id: typecheck
        name: Run typecheck
        run: pnpm typecheck
        background: true
      - id: build
        name: Build
        run: pnpm build
        background: true
      - id: wait
        name: Wait for background jobs to finish
        wait: [tests, typecheck, build]
      - id: release
        name: Build
        run: pnpm publish --access public --no-git-checks
